// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: pkg/proto/services.proto

package shorturl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cookies       string `protobuf:"bytes,1,opt,name=cookies,proto3" json:"cookies,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	LongUrl       string `protobuf:"bytes,3,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CorrelationId string `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Deleted       bool   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *Url) Reset() {
	*x = Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{0}
}

func (x *Url) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *Url) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Url) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *Url) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Url) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int32 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int32 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

type OneString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OneString string `protobuf:"bytes,1,opt,name=one_string,json=oneString,proto3" json:"one_string,omitempty"`
}

func (x *OneString) Reset() {
	*x = OneString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneString) ProtoMessage() {}

func (x *OneString) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneString.ProtoReflect.Descriptor instead.
func (*OneString) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{2}
}

func (x *OneString) GetOneString() string {
	if x != nil {
		return x.OneString
	}
	return ""
}

type CreateShort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long string `protobuf:"bytes,1,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *CreateShort) Reset() {
	*x = CreateShort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShort) ProtoMessage() {}

func (x *CreateShort) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShort.ProtoReflect.Descriptor instead.
func (*CreateShort) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShort) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type DeleteListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeleteList []*OneString `protobuf:"bytes,1,rep,name=delete_list,json=deleteList,proto3" json:"delete_list,omitempty"`
}

func (x *DeleteListRequest) Reset() {
	*x = DeleteListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListRequest) ProtoMessage() {}

func (x *DeleteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListRequest.ProtoReflect.Descriptor instead.
func (*DeleteListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteListRequest) GetDeleteList() []*OneString {
	if x != nil {
		return x.DeleteList
	}
	return nil
}

type IDParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IDParam) Reset() {
	*x = IDParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDParam) ProtoMessage() {}

func (x *IDParam) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDParam.ProtoReflect.Descriptor instead.
func (*IDParam) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{5}
}

func (x *IDParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl      string `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *PackReq) Reset() {
	*x = PackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackReq) ProtoMessage() {}

func (x *PackReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackReq.ProtoReflect.Descriptor instead.
func (*PackReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{6}
}

func (x *PackReq) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *PackReq) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *PackReq) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ReqURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ReqURL) Reset() {
	*x = ReqURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqURL) ProtoMessage() {}

func (x *ReqURL) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqURL.ProtoReflect.Descriptor instead.
func (*ReqURL) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{7}
}

func (x *ReqURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateShortURLJSONResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateShortURLJSONResponse) Reset() {
	*x = CreateShortURLJSONResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortURLJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLJSONResponse) ProtoMessage() {}

func (x *CreateShortURLJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLJSONResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLJSONResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{8}
}

func (x *CreateShortURLJSONResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type AllURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string short_url = 1;
	// string original_url = 2;
	RespUrls []*PackReq `protobuf:"bytes,1,rep,name=resp_urls,json=respUrls,proto3" json:"resp_urls,omitempty"`
}

func (x *AllURLsResponse) Reset() {
	*x = AllURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllURLsResponse) ProtoMessage() {}

func (x *AllURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllURLsResponse.ProtoReflect.Descriptor instead.
func (*AllURLsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{9}
}

func (x *AllURLsResponse) GetRespUrls() []*PackReq {
	if x != nil {
		return x.RespUrls
	}
	return nil
}

type CreateShortURLHandlerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CreateShortURLHandlerResponse) Reset() {
	*x = CreateShortURLHandlerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_services_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortURLHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLHandlerResponse) ProtoMessage() {}

func (x *CreateShortURLHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_services_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLHandlerResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLHandlerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_services_proto_rawDescGZIP(), []int{10}
}

func (x *CreateShortURLHandlerResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_pkg_proto_services_proto protoreflect.FileDescriptor

var file_pkg_proto_services_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6f, 0x6b,
	0x69, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22,
	0x39, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x2a, 0x0a, 0x09, 0x4f, 0x6e,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x65, 0x5f, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x6e, 0x65,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x21, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x49, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x4f,
	0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x07, 0x49, 0x44, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x70, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x22, 0x1a, 0x0a, 0x06, 0x52, 0x65, 0x71, 0x55, 0x52, 0x4c, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x34, 0x0a,
	0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x4a,
	0x53, 0x4f, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x41, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x75,
	0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x31, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0x94, 0x04, 0x0a, 0x08, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75,
	0x72, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x55, 0x52, 0x4c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x41, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12,
	0x15, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72,
	0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x79,
	0x49, 0x44, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x2e, 0x49, 0x44, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x0d, 0x2e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x55, 0x72, 0x6c, 0x12, 0x2d, 0x0a, 0x05, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x11, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75,
	0x72, 0x6c, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x4c, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x4a, 0x53, 0x4f, 0x4e,
	0x12, 0x10, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x55,
	0x52, 0x4c, 0x1a, 0x24, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x4a, 0x53, 0x4f, 0x4e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x32,
	0x32, 0x46, 0x61, 0x72, 0x69, 0x7a, 0x32, 0x32, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_services_proto_rawDescOnce sync.Once
	file_pkg_proto_services_proto_rawDescData = file_pkg_proto_services_proto_rawDesc
)

func file_pkg_proto_services_proto_rawDescGZIP() []byte {
	file_pkg_proto_services_proto_rawDescOnce.Do(func() {
		file_pkg_proto_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_services_proto_rawDescData)
	})
	return file_pkg_proto_services_proto_rawDescData
}

var file_pkg_proto_services_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_proto_services_proto_goTypes = []interface{}{
	(*Url)(nil),                           // 0: shorturl.Url
	(*StatsResponse)(nil),                 // 1: shorturl.StatsResponse
	(*OneString)(nil),                     // 2: shorturl.OneString
	(*CreateShort)(nil),                   // 3: shorturl.CreateShort
	(*DeleteListRequest)(nil),             // 4: shorturl.DeleteListRequest
	(*IDParam)(nil),                       // 5: shorturl.IDParam
	(*PackReq)(nil),                       // 6: shorturl.PackReq
	(*ReqURL)(nil),                        // 7: shorturl.ReqURL
	(*CreateShortURLJSONResponse)(nil),    // 8: shorturl.CreateShortURLJSONResponse
	(*AllURLsResponse)(nil),               // 9: shorturl.AllURLsResponse
	(*CreateShortURLHandlerResponse)(nil), // 10: shorturl.CreateShortURLHandlerResponse
	(*emptypb.Empty)(nil),                 // 11: google.protobuf.Empty
}
var file_pkg_proto_services_proto_depIdxs = []int32{
	2,  // 0: shorturl.DeleteListRequest.delete_list:type_name -> shorturl.OneString
	6,  // 1: shorturl.AllURLsResponse.resp_urls:type_name -> shorturl.PackReq
	11, // 2: shorturl.Services.Stats:input_type -> google.protobuf.Empty
	4,  // 3: shorturl.Services.DeleteHandler:input_type -> shorturl.DeleteListRequest
	11, // 4: shorturl.Services.GetAllURL:input_type -> google.protobuf.Empty
	3,  // 5: shorturl.Services.CreateShortURLHandler:input_type -> shorturl.CreateShort
	5,  // 6: shorturl.Services.GetShortURLByIDHandler:input_type -> shorturl.IDParam
	6,  // 7: shorturl.Services.Batch:input_type -> shorturl.PackReq
	7,  // 8: shorturl.Services.CreateShortURLJSON:input_type -> shorturl.ReqURL
	11, // 9: shorturl.Services.Ping:input_type -> google.protobuf.Empty
	1,  // 10: shorturl.Services.Stats:output_type -> shorturl.StatsResponse
	11, // 11: shorturl.Services.DeleteHandler:output_type -> google.protobuf.Empty
	9,  // 12: shorturl.Services.GetAllURL:output_type -> shorturl.AllURLsResponse
	10, // 13: shorturl.Services.CreateShortURLHandler:output_type -> shorturl.CreateShortURLHandlerResponse
	0,  // 14: shorturl.Services.GetShortURLByIDHandler:output_type -> shorturl.Url
	6,  // 15: shorturl.Services.Batch:output_type -> shorturl.PackReq
	8,  // 16: shorturl.Services.CreateShortURLJSON:output_type -> shorturl.CreateShortURLJSONResponse
	11, // 17: shorturl.Services.Ping:output_type -> google.protobuf.Empty
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_services_proto_init() }
func file_pkg_proto_services_proto_init() {
	if File_pkg_proto_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortURLJSONResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_services_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortURLHandlerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_services_proto_goTypes,
		DependencyIndexes: file_pkg_proto_services_proto_depIdxs,
		MessageInfos:      file_pkg_proto_services_proto_msgTypes,
	}.Build()
	File_pkg_proto_services_proto = out.File
	file_pkg_proto_services_proto_rawDesc = nil
	file_pkg_proto_services_proto_goTypes = nil
	file_pkg_proto_services_proto_depIdxs = nil
}
